syntax = "proto3";

option csharp_namespace = "Shared.Protos.Services.ServerNode";

package BackgroundJobsService;

import "Protos/Shared/Shared.proto";
import "Protos/Messages/ServerNode/BackgroundJobServiceMessages.proto";

service ServerNodeBackgroundJobServiceGrpc {
  rpc Create (BackgroundJobServiceMessages.BackgroundJobCreateRequest) returns (BackgroundJobServiceMessages.BackgroundJobReadReply);
  rpc Read (BackgroundJobServiceMessages.BackgroundJobReadRequest) returns (BackgroundJobServiceMessages.BackgroundJobReadReply);
  rpc ReadCollection (BackgroundJobServiceMessages.BackgroundJobReadCollectionRequest) returns (BackgroundJobServiceMessages.BackgroundJobReadCollectionReply);
  rpc Update (BackgroundJobServiceMessages.BackgroundJobUpdateRequest) returns (BackgroundJobServiceMessages.BackgroundJobReadReply);
  rpc Delete (BackgroundJobServiceMessages.BackgroundJobDeleteRequest) returns (Shared.OkReply);
}