<Project Sdk="Microsoft.NET.Sdk.Web">
    
    <ItemGroup>
        <Content Include="..\..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ServerNode.Application\ServerNode.Application.csproj"/>
        <ProjectReference Include="..\Shared\Shared.csproj"/>
    </ItemGroup>

</Project>
