<Project Sdk="Microsoft.NET.Sdk">
    

    <ItemGroup>
        <Folder Include="Handlers\" />
        <Folder Include="Mappers\"/>
        <Folder Include="Services\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ServerNode.Application\ServerNode.Application.csproj" />
      <ProjectReference Include="..\Shared\Shared.csproj" />
    </ItemGroup>

</Project>
