<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Calabonga.Microservices.Tracker"/>
        <PackageReference Include="DotNetEnv"/>
        <PackageReference Include="EntityFramework.DynamicLinq"/>
        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
        <PackageReference Include="Google.Protobuf" />
        <PackageReference Include="Grpc.Tools">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Hangfire"/>
        <PackageReference Include="Hangfire.PostgreSql"/>
        <PackageReference Include="MediatR"/>
        <PackageReference Include="MemoryPack"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Minio"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
        <PackageReference Include="prometheus-net.AspNetCore"/>
        <PackageReference Include="Serilog"/>
        <PackageReference Include="Serilog.AspNetCore"/>
        <PackageReference Include="Serilog.Enrichers.AssemblyName"/>
        <PackageReference Include="Serilog.Enrichers.Environment"/>
        <PackageReference Include="Serilog.Enrichers.GlobalLogContext"/>
        <PackageReference Include="Serilog.Enrichers.Memory"/>
        <PackageReference Include="Serilog.Enrichers.Process"/>
        <PackageReference Include="Serilog.Enrichers.Thread"/>
        <PackageReference Include="SharpZipLib" />
        <PackageReference Include="Swashbuckle.AspNetCore"/>
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations"/>
    </ItemGroup>

</Project>
