syntax = "proto3";

option csharp_namespace = "Shared.Protos.Messages.ServerNode";

package BackgroundJobServiceMessages;

import "Protos/Shared/Shared.proto";

message BackgroundJobCreateRequest {
  Shared.KeyValueEntryDto Metadata = 1;
  string Uri = 2;
}

message BackgroundJobReadRequest {
  string BackgroundJobId = 1;
}

message BackgroundJobReadCollectionRequest {
  Shared.PageModel PageModel = 1;
  string Term = 2;
}

message BackgroundJobUpdateRequest {
  string BackgroundJobId = 1;
  string State = 2;
}

message BackgroundJobDeleteRequest {
  string BackgroundJobId = 1;
}

message BackgroundJobReadReply {
  string BackgroundJobId = 1;
  string State = 2;
  Shared.EntityBaseReply EntityBase = 3;
}

message BackgroundJobReadCollectionReply {
  int32 Total = 1;
  repeated BackgroundJobReadReply Items = 2;
}